//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
recipes.remove(<icbmclassic:explosives:*>);
recipes.remove(<icbmclassic:rocketlauncher>);
recipes.remove(<icbmclassic:missile:24>);
//Don't touch me!
//#Add
recipes.addShaped(<icbmclassic:explosives:8>, [[<appliedenergistics2:tiny_tnt>, <appliedenergistics2:tiny_tnt>, <appliedenergistics2:tiny_tnt>],[<appliedenergistics2:tiny_tnt>, <icbmclassic:explosives:1>, <appliedenergistics2:tiny_tnt>], [<appliedenergistics2:tiny_tnt>, <appliedenergistics2:tiny_tnt>, <appliedenergistics2:tiny_tnt>]]);
recipes.addShaped(<icbmclassic:explosives:4>, [[<thermalfoundation:material:816>, <minecraft:fermented_spider_eye>, <thermalfoundation:material:816>],[<minecraft:fermented_spider_eye>, <icbmclassic:explosives>, <minecraft:fermented_spider_eye>], [<thermalfoundation:material:816>, <minecraft:fermented_spider_eye>, <thermalfoundation:material:816>]]);
recipes.addShaped(<icbmclassic:explosives:2>, [[<minecraft:blaze_powder>, <minecraft:blaze_powder>, <minecraft:blaze_powder>],[<minecraft:blaze_powder>, <icbmclassic:explosives:1>, <minecraft:blaze_powder>], [<minecraft:blaze_powder>, <minecraft:blaze_powder>, <minecraft:blaze_powder>]]);
recipes.addShaped(<icbmclassic:explosives:1>, [[<thermalfoundation:material:224>, <thermalfoundation:material:224>, <thermalfoundation:material:224>],[<thermalfoundation:material:224>, <icbmclassic:explosives>, <thermalfoundation:material:224>], [<thermalfoundation:material:224>, <thermalfoundation:material:224>, <thermalfoundation:material:224>]]);
recipes.addShaped(<icbmclassic:explosives> * 3, [[<thermalfoundation:material:771>, <minecraft:tnt>, <thermalfoundation:material:771>],[<minecraft:tnt>, <thermalfoundation:material:771>, <minecraft:tnt>], [<thermalfoundation:material:771>, <minecraft:tnt>, <thermalfoundation:material:771>]]);
recipes.addShaped(<icbmclassic:rocketlauncher>, [[<icbmclassic:laserdetonator>, <modernmetals:titanium_dense_plate>, <nuclearcraft:part:7>],[<modernmetals:titanium_dense_plate>, <icbmclassic:wire:1>, <modernmetals:titanium_dense_plate>], [<matteroverdrive:weapon_handle>, <modernmetals:titanium_dense_plate>, <mekanism:controlcircuit:3>]]);
recipes.addShaped(<icbmclassic:missile:24>, [[<modernmetals:titanium_plate>, <openmodularturrets:intermediate_tiered:4>, <modernmetals:titanium_plate>],[<modernmetals:titanium_plate>, <mekanism:controlcircuit:3>, <modernmetals:titanium_plate>], [<modernmetals:titanium_plate>, <forge:bucketfilled>, <modernmetals:titanium_plate>]]);
recipes.addShaped(<icbmclassic:explosives:23>, [[<enderio:block_infinity_fog>, <enderio:block_infinity_fog>, <enderio:block_infinity_fog>],[<enderio:block_infinity_fog>, <matteroverdrive:gravitational_anomaly>, <enderio:block_infinity_fog>], [<enderio:block_infinity_fog>, <enderio:block_infinity_fog>, <enderio:block_infinity_fog>]]);
recipes.addShaped(<icbmclassic:explosives:22>, [[<thermalfoundation:material:359>, <matteroverdrive:me_conversion_matrix>, <thermalfoundation:material:359>],[<matteroverdrive:me_conversion_matrix>, <icbmclassic:explosives:15>, <matteroverdrive:me_conversion_matrix>], [<thermalfoundation:material:359>, <matteroverdrive:me_conversion_matrix>, <thermalfoundation:material:359>]]);
recipes.addShaped(<icbmclassic:explosives:19>, [[<thermalfoundation:material:1026>, <thermalfoundation:material:1026>, <thermalfoundation:material:1026>],[<thermalfoundation:material:1026>, <icbmclassic:explosives>, <thermalfoundation:material:1026>], [<thermalfoundation:material:1026>, <thermalfoundation:material:1026>, <thermalfoundation:material:1026>]]);
recipes.addShaped(<icbmclassic:explosives:18>, [[<thermalfoundation:material:1025>, <thermalfoundation:material:1025>, <thermalfoundation:material:1025>],[<thermalfoundation:material:1025>, <icbmclassic:explosives>, <thermalfoundation:material:1025>], [<thermalfoundation:material:1025>, <thermalfoundation:material:1025>, <thermalfoundation:material:1025>]]);
recipes.addShaped(<icbmclassic:explosives:17>, [[<thermalfoundation:material:1024>, <thermalfoundation:material:1024>, <thermalfoundation:material:1024>],[<thermalfoundation:material:1024>, <icbmclassic:explosives:2>, <thermalfoundation:material:1024>], [<thermalfoundation:material:1024>, <thermalfoundation:material:1024>, <thermalfoundation:material:1024>]]);
recipes.addShaped(<icbmclassic:explosives:16>, [[<thermalfoundation:material:101>, <extrautils2:ingredients>, <thermalfoundation:material:101>],[<extrautils2:ingredients>, <icbmclassic:explosives>, <extrautils2:ingredients>], [<thermalfoundation:material:101>, <extrautils2:ingredients>, <thermalfoundation:material:101>]]);
recipes.addShaped(<icbmclassic:explosives:15>, [[<thermalfoundation:material:352>, <icbmclassic:explosives>, <thermalfoundation:material:352>],[<icbmclassic:explosives>, <nuclearcraft:plutonium:4>, <icbmclassic:explosives>], [<thermalfoundation:material:352>, <icbmclassic:explosives>, <thermalfoundation:material:352>]]);
recipes.addShaped(<icbmclassic:explosives:13>, [[<thermalfoundation:material:352>, <thermalfoundation:material:352>, <thermalfoundation:material:352>],[<nuclearcraft:dust:7>, <icbmclassic:explosives>, <nuclearcraft:dust:7>], [<thermalfoundation:material:352>, <thermalfoundation:material:352>, <thermalfoundation:material:352>]]);
recipes.addShaped(<icbmclassic:explosives:9>, [[<ebwizardry:poison_bomb>, <ebwizardry:poison_bomb>, <ebwizardry:poison_bomb>],[<ebwizardry:poison_bomb>, <icbmclassic:explosives:4>, <ebwizardry:poison_bomb>], [<ebwizardry:poison_bomb>, <ebwizardry:poison_bomb>, <ebwizardry:poison_bomb>]]);
//File End
