//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
recipes.remove(<woot:stygianironplate>);
recipes.remove(<extraplanets:advanced_launch_pad> * 9);
recipes.remove(<galacticraftcore:landing_pad> * 9);
recipes.remove(<galacticraftcore:rocket_workbench>);
recipes.remove(<galacticraftcore:fuel_loader>);
recipes.remove(<icbmclassic:circuit:1>);
recipes.remove(<extraplanets:tier5_items:2>);
recipes.remove(<extraplanets:nose_cone_tier4>);
recipes.remove(<galacticraftcore:refinery>);
recipes.remove(<extraplanets:tier4_items:1>);
recipes.remove(<extraplanets:tier4_items>);
recipes.remove(<extraplanets:tier4_items:2>);
recipes.remove(<extraplanets:tier4_items:1>);
recipes.remove(<extraplanets:tier5_items>);
recipes.remove(<extraplanets:nose_cone_tier5>);
recipes.remove(<extraplanets:tier5_items:1>);
recipes.remove(<extraplanets:tier6_items:2>);
recipes.remove(<extraplanets:tier6_items>);
recipes.remove(<extraplanets:nose_cone_tier6>);
recipes.remove(<extraplanets:tier6_items:1>);
recipes.remove(<extraplanets:tier7_items:2>);
recipes.remove(<extraplanets:tier7_items>);
recipes.remove(<extraplanets:tier7_items:1>);
recipes.remove(<extraplanets:nose_cone_tier7>);
recipes.remove(<extraplanets:tier8_items:2>);
recipes.remove(<extraplanets:tier8_items>);
recipes.remove(<extraplanets:nose_cone_tier8>);
recipes.remove(<extraplanets:tier8_items:1>);
recipes.remove(<extraplanets:tier9_items:1>);
recipes.remove(<extraplanets:tier9_items:1>);
recipes.remove(<extraplanets:tier9_items:2>);
recipes.remove(<extraplanets:tier9_items>);
recipes.remove(<extraplanets:nose_cone_tier9>);
recipes.remove(<mekanism:tierinstaller>);
recipes.remove(<mekanism:tierinstaller:1>);
recipes.remove(<mekanism:tierinstaller:2>);
recipes.remove(<mekanism:tierinstaller:3>);
recipes.remove(<mekanism:controlcircuit:3>);
recipes.remove(<mekanism:controlcircuit:2>);
recipes.remove(<mekanism:controlcircuit:1>);
recipes.remove(<extraplanets:tier10_items:1>);
recipes.remove(<extraplanets:nose_cone_tier10>);
recipes.remove(<extraplanets:tier10_items>);
recipes.remove(<extraplanets:tier10_items:2>);
//Don't touch me!
//#Add
recipes.addShaped(<minecraft:skull:1>, [[<quark:black_ash>, <quark:black_ash>, <quark:black_ash>],[<extrautils2:ingredients:10>, <ore:boneWithered>, <extrautils2:ingredients:10>], [<quark:black_ash>, <quark:black_ash>, <quark:black_ash>]]);
recipes.addShaped(<extraplanets:advanced_launch_pad> * 9, [[<techguns:itemshared:53>, <techguns:itemshared:53>, <techguns:itemshared:53>],[<jaopca:item_platedensemithril>, <jaopca:item_platedensemithril>, <jaopca:item_platedensemithril>], [<techguns:itemshared:45>, <techguns:itemshared:45>, <techguns:itemshared:45>]]);
recipes.addShaped(<galacticraftcore:landing_pad> * 9, [[<ore:plateDenseTungsten>, <matteroverdrive:h_compensator>, <ore:plateDenseTungsten>],[<ore:plateDenseTitanium>, <ore:plateDenseTitanium>, <ore:plateDenseTitanium>], [<ore:blockSteel>, <ore:blockSteel>, <ore:blockSteel>]]);
recipes.addShaped(<harvestcraft:windygarden>, [[<actuallyadditions:item_fertilizer>, <environmentaltech:litherite_crystal>, <actuallyadditions:item_fertilizer>],[<silentgems:craftingmaterial:1>, <ore:gemPeridot>, <silentgems:craftingmaterial:1>], [<actuallyadditions:item_fertilizer>, <environmentaltech:litherite_crystal>, <actuallyadditions:item_fertilizer>]]);
recipes.addShaped(<harvestcraft:aridgarden>, [[<actuallyadditions:item_fertilizer>, <environmentaltech:litherite_crystal>, <actuallyadditions:item_fertilizer>],[<silentgems:craftingmaterial:1>, <ore:gemRuby>, <silentgems:craftingmaterial:1>], [<actuallyadditions:item_fertilizer>, <environmentaltech:litherite_crystal>, <actuallyadditions:item_fertilizer>]]);
recipes.addShaped(<harvestcraft:tropicalgarden>, [[<actuallyadditions:item_fertilizer>, <environmentaltech:litherite_crystal>, <actuallyadditions:item_fertilizer>],[<silentgems:craftingmaterial:1>, <ore:gemTopaz>, <silentgems:craftingmaterial:1>], [<actuallyadditions:item_fertilizer>, <environmentaltech:litherite_crystal>, <actuallyadditions:item_fertilizer>]]);
recipes.addShaped(<harvestcraft:soggygarden>, [[<actuallyadditions:item_fertilizer>, <environmentaltech:litherite_crystal>, <actuallyadditions:item_fertilizer>],[<silentgems:craftingmaterial:1>, <ore:gemApatite>, <silentgems:craftingmaterial:1>], [<actuallyadditions:item_fertilizer>, <environmentaltech:litherite_crystal>, <actuallyadditions:item_fertilizer>]]);
recipes.addShaped(<harvestcraft:shadedgarden>, [[<actuallyadditions:item_fertilizer>, <environmentaltech:litherite_crystal>, <actuallyadditions:item_fertilizer>],[<silentgems:craftingmaterial:1>, <ore:gemEmerald>, <silentgems:craftingmaterial:1>], [<actuallyadditions:item_fertilizer>, <environmentaltech:litherite_crystal>, <actuallyadditions:item_fertilizer>]]);
recipes.addShaped(<harvestcraft:frostgarden>, [[<actuallyadditions:item_fertilizer>, <environmentaltech:litherite_crystal>, <actuallyadditions:item_fertilizer>],[<silentgems:craftingmaterial:1>, <ore:gemTanzanite>, <silentgems:craftingmaterial:1>], [<actuallyadditions:item_fertilizer>, <environmentaltech:litherite_crystal>, <actuallyadditions:item_fertilizer>]]);
recipes.addShaped(<galacticraftcore:fuel_loader>, [[<galacticraftcore:basic_item:10>, <galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:10>],[<thermalfoundation:material:264>, <thermalexpansion:tank>, <thermalfoundation:material:264>], [<galacticraftcore:basic_item:10>, <galacticraftcore:basic_item:13>, <galacticraftcore:basic_item:10>]]);
recipes.addShaped(<galacticraftcore:rocket_workbench>, [[<galacticraftcore:basic_item:9>, <appliedenergistics2:part:360>, <galacticraftcore:basic_item:9>],[<plustic:osmiridiumblock>, <extraplanets:wafer>, <plustic:osmiridiumblock>], [<galacticraftcore:basic_item:9>, <matteroverdrive:forcefield_emitter>, <galacticraftcore:basic_item:9>]]);
recipes.addShaped(<extraplanets:schematic_tier10>, [[<extraplanets:tier10_items:3>, <extraplanets:eris:7>, <extraplanets:tier10_items:3>],[<extraplanets:eris:7>, <extraplanets:item_tier10_rocket:1>, <extraplanets:eris:7>], [<extraplanets:tier10_items:3>, <extraplanets:eris:7>, <extraplanets:tier10_items:3>]]);
recipes.addShaped(<extraplanets:schematic_tier9>, [[<extraplanets:tier9_items:3>, <extraplanets:pluto:7>, <extraplanets:tier9_items:3>],[<extraplanets:pluto:7>, <extraplanets:item_tier9_rocket>, <extraplanets:pluto:7>], [<extraplanets:tier9_items:3>, <extraplanets:pluto:7>, <extraplanets:tier9_items:3>]]);
recipes.addShaped(<extraplanets:schematic_tier8>, [[<extraplanets:tier8_items:3>, <extraplanets:neptune:7>, <extraplanets:tier8_items:3>],[<extraplanets:neptune:7>, <extraplanets:item_tier8_rocket>, <extraplanets:neptune:7>], [<extraplanets:tier8_items:3>, <extraplanets:neptune:7>, <extraplanets:tier8_items:3>]]);
recipes.addShaped(<extraplanets:schematic_tier7>, [[<extraplanets:tier7_items:3>, <extraplanets:uranus:4>, <extraplanets:tier7_items:3>],[<extraplanets:uranus:4>, <extraplanets:item_tier7_rocket>, <extraplanets:uranus:4>], [<extraplanets:tier7_items:3>, <extraplanets:uranus:4>, <extraplanets:tier7_items:3>]]);
recipes.addShaped(<extraplanets:schematic_tier6>, [[<extraplanets:tier6_items:3>, <extraplanets:saturn:7>, <extraplanets:tier6_items:3>],[<extraplanets:saturn:7>, <extraplanets:item_tier6_rocket>, <extraplanets:saturn:7>], [<extraplanets:tier6_items:3>, <extraplanets:saturn:7>, <extraplanets:tier6_items:3>]]);
recipes.addShaped(<extraplanets:schematic_tier5>, [[<extraplanets:tier5_items:3>, <extraplanets:jupiter:8>, <extraplanets:tier5_items:3>],[<extraplanets:jupiter:8>, <extraplanets:item_tier5_rocket>, <extraplanets:jupiter:8>], [<extraplanets:tier5_items:3>, <extraplanets:jupiter:8>, <extraplanets:tier5_items:3>]]);
recipes.addShaped(<extraplanets:schematic_tier4>, [[<extraplanets:tier4_items:3>, <extraplanets:mercury:7>, <extraplanets:tier4_items:3>],[<extraplanets:mercury:7>, <extraplanets:item_tier4_rocket>, <extraplanets:mercury:7>], [<extraplanets:tier4_items:3>, <extraplanets:mercury:7>, <extraplanets:tier4_items:3>]]);
recipes.addShaped(<galacticraftplanets:schematic>, [[<galacticraftplanets:item_basic_mars:3>, <galacticraftplanets:mars:8>, <galacticraftplanets:item_basic_mars:3>],[<galacticraftplanets:mars:8>, <galacticraftplanets:rocket_t2>, <galacticraftplanets:mars:8>], [<galacticraftplanets:item_basic_mars:3>, <galacticraftplanets:mars:8>, <galacticraftplanets:item_basic_mars:3>]]);
recipes.addShaped(<galacticraftcore:schematic:1>, [[<galacticraftcore:heavy_plating>, <galacticraftcore:basic_block_core:12>, <galacticraftcore:heavy_plating>],[<galacticraftcore:basic_block_core:12>, <galacticraftcore:rocket_t1>, <galacticraftcore:basic_block_core:12>], [<galacticraftcore:heavy_plating>, <galacticraftcore:basic_block_core:12>, <galacticraftcore:heavy_plating>]]);
recipes.addShaped(<galacticraftcore:dungeonfinder>, [[<draconicevolution:chaos_shard:1>, <exchangers:te_exchanger_core_tier3>, <draconicevolution:chaos_shard:1>],[<exchangers:mekanism_exchanger_core_tier3>, <minecraft:compass>, <exchangers:eio_exchanger_core_tier3>], [<draconicevolution:chaos_shard:1>, <exchangers:ie_exchanger_core_tier3>, <draconicevolution:chaos_shard:1>]]);
recipes.addShaped(<extraplanets:tier4_items:1>, [[<extrautils2:decorativesolid:3>, <minecraft:diamond>, <extrautils2:decorativesolid:3>],[<extrautils2:decorativesolidwood:1>, <galacticraftcore:fuel_canister_partial:1>, <extrautils2:decorativesolidwood:1>], [<nuclearcraft:cooler:10>, <draconicevolution:particle_generator>, <nuclearcraft:cooler:10>]]);
recipes.addShaped(<extraplanets:nose_cone_tier4>, [[null, <environmentaltech:lightning_rod>, null],[<thermalfoundation:storage_alloy:3>, <mekanism:tierinstaller>, <thermalfoundation:storage_alloy:3>], [<silentgems:gemsuper:*>, <danknull:dank_null:3>, <silentgems:gemsuper:*>]]);
recipes.addShaped(<extraplanets:tier4_items>, [[<actuallyadditions:block_testifi_bucks_white_wall>, <draconicevolution:draconic_core>, <actuallyadditions:block_testifi_bucks_white_wall>],[<extracells:storage.fluid>, <draconicevolution:infused_obsidian>, <extracells:storage.gas>], [<extrautils2:opinium:2>, <mekanism:jetpack>, <extrautils2:opinium:2>]]);
recipes.addShaped(<extraplanets:tier4_items:2>, [[null, <enderio:block_alloy:4>, null],[<enderio:block_alloy:4>, <appliedenergistics2:storage_cell_4k>, <enderio:block_alloy:4>], [<actuallyadditions:block_testifi_bucks_white_wall>, <extrautils2:decorativesolid:3>, <actuallyadditions:block_testifi_bucks_white_wall>]]);
recipes.addShaped(<extraplanets:tier5_items:2>, [[null, <enderio:block_alloy:3>, null],[<enderio:block_alloy:3>, <appliedenergistics2:storage_cell_16k>, <enderio:block_alloy:3>], [<environmentaltech:litherite>, <extrautils2:ingredients:2>, <environmentaltech:litherite>]]);
recipes.addShaped(<extraplanets:tier5_items>, [[<actuallyadditions:block_crystal_empowered:3>, <draconicevolution:particle_generator:2>, <actuallyadditions:block_crystal_empowered:3>],[<extracells:storage.fluid:1>, <draconicevolution:diss_enchanter>, <extracells:storage.gas:1>], [<extrautils2:opinium:3>, <mekanism:armoredjetpack>, <extrautils2:opinium:3>]]);
recipes.addShaped(<extraplanets:nose_cone_tier5>, [[null, <draconicevolution:energy_crystal:3>, null],[<thermalfoundation:storage_alloy:4>, <mekanism:controlcircuit:1>, <thermalfoundation:storage_alloy:4>], [<silentgems:craftingmaterial>, <danknull:dank_null:4>, <silentgems:craftingmaterial>]]);
recipes.addShaped(<extraplanets:tier5_items:1>, [[<ore:blockLitherite>, <silentgems:craftingmaterial:4>, <ore:blockLitherite>],[<extrautils2:klein>, <draconicevolution:crafting_injector>, <extrautils2:klein>], [<nuclearcraft:nuclear_furnace_idle>, <draconicevolution:dislocator>, <nuclearcraft:nuclear_furnace_idle>]]);
recipes.addShaped(<extraplanets:tier6_items:2>, [[null, <enderio:block_alloy>, null],[<enderio:block_alloy>, <appliedenergistics2:storage_cell_64k>, <enderio:block_alloy>], [<ore:blockErodium>, <extrautils2:ingredients:4>, <ore:blockErodium>]]);
recipes.addShaped(<extraplanets:tier6_items>, [[<actuallyadditions:block_crystal_empowered:5>, <draconicevolution:wyvern_energy_core>, <actuallyadditions:block_crystal_empowered:5>],[<extracells:storage.fluid:2>, <draconicevolution:chaos_shard:3>, <extracells:storage.gas:2>], [<extrautils2:opinium:4>, <simplyjetpacks:itemjetpack:14>, <extrautils2:opinium:4>]]);
recipes.addShaped(<extraplanets:nose_cone_tier6>, [[null, <draconicevolution:entity_detector>, null],[<thermalfoundation:storage_alloy:2>, <mekanism:tierinstaller:1>, <thermalfoundation:storage_alloy:2>], [<silentgems:craftingmaterial:1>, <openmodularturrets:intermediate_tiered>, <silentgems:craftingmaterial:1>]]);
recipes.addShaped(<extraplanets:tier6_items:1>, [[<ore:blockErodium>, <minecraft:nether_star>, <ore:blockErodium>],[<extrautils2:suncrystal>, <draconicevolution:energy_infuser>, <extrautils2:suncrystal>], [<nuclearcraft:fission_controller_new_idle>, <draconicevolution:dislocator_receptacle>, <nuclearcraft:fission_controller_new_idle>]]);
recipes.addShaped(<extraplanets:tier7_items:2>, [[null, <enderio:block_alloy:5>, null],[<enderio:block_alloy:5>, <extracells:storage.physical>, <enderio:block_alloy:5>], [<ore:blockKyronite>, <extrautils2:ingredients:11>, <ore:blockKyronite>]]);
recipes.addShaped(<extraplanets:tier7_items>, [[<actuallyadditions:block_crystal_empowered>, <draconicevolution:wyvern_core>, <actuallyadditions:block_crystal_empowered>],[<extracells:storage.fluid:3>, <draconicevolution:chaos_shard:2>, <extracells:storage.gas:3>], [<extrautils2:opinium:5>, <simplyjetpacks:itemjetpack:15>, <extrautils2:opinium:5>]]);
recipes.addShaped(<extraplanets:nose_cone_tier7>, [[null, <draconicevolution:energy_crystal:4>, null],[<thermalfoundation:storage_alloy:1>, <mekanism:controlcircuit:2>, <thermalfoundation:storage_alloy:1>], [<silentgems:craftingmaterial:14>, <openmodularturrets:intermediate_tiered:1>, <silentgems:craftingmaterial:14>]]);
recipes.addShaped(<extraplanets:tier7_items:1>, [[<environmentaltech:kyronite>, <exchangers:te_exchanger_core_tier3>, <environmentaltech:kyronite>],[<extrautils2:ingredients:3>, <draconicevolution:entity_detector:1>, <extrautils2:ingredients:3>], [<nuclearcraft:rtg_uranium>, <draconicevolution:draconium_block>, <nuclearcraft:rtg_uranium>]]);
recipes.addShaped(<extraplanets:tier8_items:2>, [[null, <enderio:block_alloy:7>, null],[<enderio:block_alloy:7>, <extracells:storage.physical:1>, <enderio:block_alloy:7>], [<ore:blockPladium>, <extrautils2:ingredients:12>, <ore:blockPladium>]]);
recipes.addShaped(<extraplanets:tier8_items>, [[<actuallyadditions:block_crystal_empowered:1>, <draconicevolution:draconic_energy_core>, <actuallyadditions:block_crystal_empowered:1>],[<extracells:storage.fluid:4>, <draconicevolution:chaos_shard:1>, <extracells:storage.gas:4>], [<extrautils2:opinium:6>, <simplyjetpacks:itemjetpack:16>, <extrautils2:opinium:6>]]);
recipes.addShaped(<extraplanets:nose_cone_tier8>, [[null, <draconicevolution:dislocator_advanced>, null],[<ore:blockLumium>, <mekanism:tierinstaller:2>, <ore:blockLumium>], [<silentgems:chaospylon>, <openmodularturrets:intermediate_tiered:2>, <silentgems:chaospylon>]]);
recipes.addShaped(<extraplanets:tier8_items:1>, [[<ore:blockPladium>, <matteroverdrive:gravitational_anomaly>, <ore:blockPladium>],[<extrautils2:ingredients:6>, <draconicevolution:crafting_injector:1>, <extrautils2:ingredients:6>], [<nuclearcraft:rtg_americium>, <draconicevolution:celestial_manipulator>, <nuclearcraft:rtg_americium>]]);
recipes.addShaped(<extraplanets:tier9_items:1>, [[<ore:blockIonite>, <techguns:itemshared:131>, <ore:blockIonite>],[<extrautils2:ingredients:15>, <draconicevolution:crafting_injector:2>, <extrautils2:ingredients:15>], [<nuclearcraft:rtg_plutonium>, <draconicevolution:draconic_block>, <nuclearcraft:rtg_plutonium>]]);
recipes.addShaped(<extraplanets:tier9_items:2>, [[null, <enderio:block_alloy:1>, null],[<enderio:block_alloy:1>, <extracells:storage.physical:2>, <enderio:block_alloy:1>], [<ore:blockIonite>, <extrautils2:ingredients:17>, <ore:blockIonite>]]);
recipes.addShaped(<extraplanets:tier9_items>, [[<actuallyadditions:block_crystal_empowered:2>, <draconicevolution:awakened_core>, <actuallyadditions:block_crystal_empowered:2>],[<extracells:storage.fluid:5>, <draconicevolution:chaos_shard>, <extracells:storage.gas:5>], [<extrautils2:opinium:7>, <simplyjetpacks:itemjetpack:17>, <extrautils2:opinium:7>]]);
recipes.addShaped(<extraplanets:nose_cone_tier9>, [[null, <draconicevolution:energy_crystal:5>, null],[<thermalfoundation:storage_alloy:5>, <mekanism:controlcircuit:3>, <thermalfoundation:storage_alloy:5>], [<silentgems:chaospylon:1>, <openmodularturrets:intermediate_tiered:3>, <silentgems:chaospylon:1>]]);
recipes.addShaped(<extraplanets:tier10_items:2>, [[null, <enderio:block_alloy:2>, null],[<enderio:block_alloy:2>, <extracells:storage.physical:3>, <enderio:block_alloy:2>], [<ore:blockAethium>, <extrautils2:unstableingots>, <ore:blockAethium>]]);
recipes.addShaped(<extraplanets:tier10_items:1>, [[<ore:blockAethium>, <techguns:antigravpack>, <ore:blockAethium>],[<extrautils2:ingredients:16>, <draconicevolution:crafting_injector:3>, <extrautils2:ingredients:16>], [<nuclearcraft:rtg_californium>, <draconicevolution:reactor_component>, <nuclearcraft:rtg_californium>]]);
recipes.addShaped(<extraplanets:tier10_items>, [[<actuallyadditions:block_crystal_empowered:4>, <draconicevolution:chaotic_core>, <actuallyadditions:block_crystal_empowered:4>],[<extracells:storage.gas:6>, <draconicevolution:reactor_core>, <extracells:storage.fluid:6>], [<extrautils2:opinium:8>, <simplyjetpacks:itemjetpack:18>, <extrautils2:opinium:8>]]);
recipes.addShaped(<extraplanets:nose_cone_tier10>, [[null, <minecraft:end_crystal>, null],[<thermalfoundation:storage_alloy:7>, <mekanism:tierinstaller:3>, <thermalfoundation:storage_alloy:7>], [<silentgems:craftingmaterial:2>, <openmodularturrets:intermediate_tiered:4>, <silentgems:craftingmaterial:2>]]);
recipes.addShaped(<mekanism:tierinstaller>, [[<actuallyadditions:block_crystal_empowered:1>, <enderio:item_alloy_ingot:3>, <actuallyadditions:block_crystal_empowered:1>],[<silentgems:craftingmaterial>, <mekanism:controlcircuit>, <silentgems:craftingmaterial>], [<actuallyadditions:block_crystal_empowered:1>, <environmentaltech:kyronite_crystal>, <actuallyadditions:block_crystal_empowered:1>]]);
recipes.addShaped(<mekanism:tierinstaller:1>, [[<actuallyadditions:block_crystal_empowered>, <enderio:item_alloy_ingot:3>, <actuallyadditions:block_crystal_empowered>],[<silentgems:craftingmaterial:1>, <mekanism:controlcircuit:1>, <silentgems:craftingmaterial:1>], [<actuallyadditions:block_crystal_empowered>, <environmentaltech:pladium_crystal>, <actuallyadditions:block_crystal_empowered>]]);
recipes.addShaped(<mekanism:tierinstaller:2>, [[<actuallyadditions:block_crystal_empowered:2>, <enderio:item_alloy_ingot:3>, <actuallyadditions:block_crystal_empowered:2>],[<minecraft:nether_star>, <mekanism:controlcircuit:2>, <minecraft:nether_star>], [<actuallyadditions:block_crystal_empowered:2>, <environmentaltech:ionite_crystal>, <actuallyadditions:block_crystal_empowered:2>]]);
recipes.addShaped(<mekanism:tierinstaller:3>, [[<actuallyadditions:block_crystal_empowered:4>, <enderio:item_alloy_ingot:3>, <actuallyadditions:block_crystal_empowered:4>],[<actuallyadditions:item_misc:19>, <mekanism:controlcircuit:3>, <actuallyadditions:item_misc:19>], [<actuallyadditions:block_crystal_empowered:4>, <environmentaltech:aethium_crystal>, <actuallyadditions:block_crystal_empowered:4>]]);
recipes.addShaped(<mekanism:controlcircuit:3>, [[<ore:ingotVibrantAlloy>, <ore:ingotEnderium>, <ore:ingotVibrantAlloy>],[<mekanism:atomicalloy>, <mekanism:controlcircuit:2>, <mekanism:atomicalloy>], [<ore:ingotVibrantAlloy>, <ore:ingotEnderium>, <ore:ingotVibrantAlloy>]]);
recipes.addShaped(<mekanism:controlcircuit:2>, [[<ore:ingotEnergeticAlloy>, <ore:ingotSignalum>, <ore:ingotEnergeticAlloy>],[<mekanism:reinforcedalloy>, <mekanism:controlcircuit:1>, <mekanism:reinforcedalloy>], [<ore:ingotEnergeticAlloy>, <ore:ingotSignalum>, <ore:ingotEnergeticAlloy>]]);
recipes.addShaped(<mekanism:controlcircuit:1>, [[<ore:ingotSoularium>, <ore:ingotInvar>, <ore:ingotSoularium>],[<mekanism:enrichedalloy>, <mekanism:controlcircuit>, <mekanism:enrichedalloy>], [<ore:ingotSoularium>, <ore:ingotInvar>, <ore:ingotSoularium>]]);
//File End
